import type { OrderStatus } from '~/data/operations';
export interface StaffIdentity { id: string; email: string; role: 'owner' | 'manager' }
export interface StoredItem { id: string; product_name: string; variant_description: string; quantity: number; unit_price_minor: number; line_total_minor: number; load_units?:number|null; category_counts?:Record<string,number>|null; rules_version?:number|null; snapshot?:{variant?:{sku?:string;names?:Record<string,string>};personalization?:string;options?:Array<{id:string;label:Record<string,string>;price_delta_minor:number}>;components?:Record<string,string|number|boolean>;production_rules?:Record<string,unknown>;source?:string}|null }
export interface StoredEvent { id: string; revision: number; kind: string; old_status: string|null; new_status: string; actor_id:string|null; details:Record<string,unknown>; created_at: string }
export interface StoredNote { id:string;order_revision:number;actor_id:string;body:string;created_at:string }
export interface StoredNotificationDelivery { id: string; event: string; channel: string; status: 'pending' | 'sending' | 'sent' | 'failed' | 'manual_required' | 'simulated'; attempts: number; available_at:string; last_error: string | null; sent_at: string | null }
export interface StaffMember {id:string;role:string;label:string}
export interface StoredDeliveryAttempt {id:string;delivery_kind:string;delivery_id:string;attempt:number;status:string;error_code:string|null;actor_id:string|null;created_at:string;finished_at:string|null}
export interface StoredOrder { assigned_to:string|null;order_delivery_attempts:StoredDeliveryAttempt[]; production_load: number|null; production_assessment?:{source?:string;reason?:string}|null; total_minor:number; category_counts:Record<string,number>|null; reservation_expires_at:string|null; rules_version:number|null; id: string; revision: number; customer_name: string; customer_contact: string; source: string; status: OrderStatus; fulfillment: string; delivery_address: string | null; delivery_minor: number; scheduled_start: string; scheduled_end: string; note: string; is_demo: boolean; created_at: string; order_items: StoredItem[]; order_events: StoredEvent[]; order_notes:StoredNote[]; order_notification_deliveries: StoredNotificationDelivery[]; order_change_deliveries: StoredNotificationDelivery[] }
export interface StoredConversation { id: string; channel: string; mode: string; assigned_to: string | null; updated_at: string; customers: { display_name: string } | null }
export interface StoredMessage { id: string; sender: string; body: string; source?: string | null; created_at: string }
export interface StoredKnowledge { id: string; slug: string; title: string; body: string; locale: 'ru' | 'en' | 'th'; visibility: 'public' | 'internal'; status: 'draft' | 'published' | 'archived'; version: number; updated_at: string }
